import type { Template } from "@/types";
import { getCategoryLabel } from "@/data/categories";

// Strip HTML tags from tip strings (they contain <strong> etc.)
function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, "");
}

function formatDate(): string {
  return new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

export function exportFavoritesAsMarkdown(templates: Template[]): void {
  if (templates.length === 0) return;

  const sections = templates
    .map(
      (t) => `## ${t.title}

**Category:** ${getCategoryLabel(t.cat)}

${t.desc}

\`\`\`
${t.code}
\`\`\`
${t.tip ? `\n> **Tip:** ${stripHtml(t.tip)}\n` : ""}`
    )
    .join("\n---\n\n");

  const markdown = `# PromptForge — My Favorites
*Exported on ${formatDate()} · ${templates.length} template${templates.length !== 1 ? "s" : ""}*

---

${sections}

---
*Generated by [PromptForge](https://github.com/)*
`;

  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `promptforge-favorites-${Date.now()}.md`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export function exportAllAsMarkdown(templates: Template[]): void {
  const byCategory: Record<string, Template[]> = {};
  templates.forEach((t) => {
    if (!byCategory[t.cat]) byCategory[t.cat] = [];
    byCategory[t.cat].push(t);
  });

  const sections = Object.entries(byCategory)
    .map(([cat, ts]) => {
      const catTemplates = ts
        .map(
          (t) => `### ${t.title}

${t.desc}

\`\`\`
${t.code}
\`\`\`
${t.tip ? `\n> **Tip:** ${stripHtml(t.tip)}\n` : ""}`
        )
        .join("\n\n");

      return `## ${getCategoryLabel(cat)}\n\n${catTemplates}`;
    })
    .join("\n\n---\n\n");

  const markdown = `# PromptForge — Complete Template Library
*Exported on ${formatDate()} · ${templates.length} templates*

---

${sections}

---
*Generated by [PromptForge](https://github.com/)*
`;

  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `promptforge-all-templates-${Date.now()}.md`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
